### ISSUE TITLE
Support for non-QWERTY keyboard layouts?

### ISSUE THREAD

**Issue by dottjt** [wiffbi/Kimidi#4]
Thanks for the great work on this! I've noticed on my colemak keyboard that the shortcuts only work with QWERTY keys (or is this due to how Selected Track Control is configured?). Is there plans to support other keyboard layouts?

**Comment by wiffbi** [comment]
Selected Track Control listens to MIDI commands triggered by Kimidi. Kimidi is configured through a plist-file inside the app-bundle, so that could be edited (look inside the bundle at Resources/MIDIActions.plist – you will get a warning due to macOS security if you edit that file though). Kimidi should look for a plist inside a user-folder first, but currently doesn’t – so that is a feature to implement at some time. Keys are defined by a so called keyCode (that is how they are bound to the global keyboard shortbut listener), so I guess keyCodes are bound to the actual transmitted code of the keyboard – which later is mapped to a letter. So looking at your colemak-layout vs. QWERTY you need to press different keys. E.G. instead to `ctrl-s` to solo, you need to press `ctrl-r` – `R` on colemak is where `S` is on QWERTY.

To find out, what keycodes you need, I used the wonderful https://manytricks.com/keycodes/ – so if you want to edit your MIDIActions.plist, you might want to give this a try.

As the key-mapping in Kimidi is done very low-level it used keyCodes. I currently see no easy way to change that to a letter-based system that respects the selected keyboard-layout, I will close this.

**Comment by wiffbi** [comment]
Created new issue #5 to support loading MIDIActions.plist from a user location (e.g. ./Library/Preferences)

**Comment by dottjt** [comment]
Thanks for getting back, I really appreciate it. 

I seem able to edit the `Resources/MIDIActions.plist` file via vscode, so that looks like an option for the time being. You could potentially setup some kind of symbolic link for the user to edit, although I'm not sure how that would work for Windows. 

What I actually did to make this work before I realised there was a MIDIActions.plist file, was to edit the scripts inside of Selected Track Control - which is a huge hack, and doesn't work beyond the predefined shortcuts within Kimidi.  

I also had another question which I couldn't quite figure out, but what does this syntax refer to:

```
<key>cc</key>
<integer>36</integer>
```

as well as this:

```
<key>alphaLock</key>
<true/>
```

**Comment by wiffbi** [comment]
Regarding Windows and symbolic links: Kimidi is a macOS-only app, so that should not be a problem. But in issue #5 I will look into it to solve it „correctly“.

Your approach with changing STC is possible, but as you already realized, limits you to the keyboard shortcuts existing in Kimidi. So changing the keyboard-shortcuts inside Kimidi makes more sense. If you want to keep all shortcuts as is, but have them mapped to your keyboard layout, you should only need to edit the numbers for the `keyCode` values.

Both your code examples are part of the way, plist-files do key-based dictionaries.

`<key>cc</key>
<integer>36</integer>`

defines a keyboard shortcut to send a MIDI-message with CC number 36 (values are 127 when pressed and 0 when released).

`<key>alphaLock</key>
<true/>`

says that this keyboard shortcut uses the alphaLock (a.k.a. CAPS-Lock) key.
